import CommonHeader from "@/components/ui/common-header";
import "../globals.css";
import AppNavigationBar from "@/components/ui/app-navigation-bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CommonLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <div className="p-6">
          <CommonHeader />
          <main>
            {children}
          </main>
        </div>
        <AppNavigationBar />
      </body>
    </html>
  );
}
